---
# tasks file for orcle client
- name: enable nfs-related services
  service:
   name: "{{ item }}"
   enabled: true
   state: started
  with_items:
  - rpcbind
  - nfs-lock
  when: ansible_distribution != "AIX"

- name: mount repository on linux
  mount:
    name: "/mnt{{ software_repository_path }}"
    src: "{{ hostvars[groups['repository-server'][0]]['ansible_default_ipv4']['address'] }}:{{ software_repository_path }}"
    fstype: nfs
    state: mounted
  when: ansible_distribution != "AIX"

- name: mount repository on aix
  command: /usr/sbin/mknfsmnt -f "/mnt{{ software_repository_path }}" -d "{{ software_repository_path }}" -h "{{ hostvars[groups['repository-server'][0]]['ansible_default_ipv4']['address'] }}" -M sys -N -a -t rw -w bg -Y -Z -X -H -j -q -g
  when: ansible_distribution == "AIX"

- name: create groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - sse_role

- name: create user
  user:
    name: "{{ item }}"
    state: present
    group: sse_role
    groups: sse_role,oinstall
  with_items:
    - siebel

- name: create siebel_base
  file:
    path: "{{item}}"
    state: directory
    mode: 0775
    owner: siebel
    group: sse_role
  with_items:
    - "{{siebel_base_path}}"
    - "{{siebel_base_path}}/oracle_client/oraInventory"

- name: create siebel gw oraInventory
  blockinfile:
    path: "{{siebel_base_path}}/oracle_client/oraInventory/oraInst.loc"
    create: yes
    mode: 0775
    owner: siebel
    group: sse_role
    block: |
       inventory_loc={{siebel_base_path}}/oracle_client/oraInventory
       inst_group=siebel

- name: get java_home on linux
  find:
    paths: "/opt/"
    patterns: "jdk*"
    file_type: directory
  register: java_home
  when: ansible_distribution != "AIX"
  
- name: get java_home on aix
  find:
    paths: "/usr/"
    patterns: "java71_64"
    file_type: directory
  register: java_home
  when: ansible_distribution == "AIX"

- name: create siebel .bash_profile
  blockinfile:
    path: /home/siebel/.bash_profile
    create: yes
    block: |	   
       # Oracle Settings
       TMP={{siebel_base_path}}/tmp; export TMP
       TMPDIR=$TMP; export TMPDIR
       ORACLE_BASE={{siebel_base_path}}/oracle_client; export ORACLE_BASE
       ORACLE_HOME={{siebel_base_path}}/oracle_client/client; export ORACLE_HOME
       ORACLE_SID=orcl; export ORACLE_SID
       PATH=/usr/sbin:$PATH; export PATH
       PATH=$ORACLE_HOME/bin:$PATH; export PATH
       LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib; export LD_LIBRARY_PATH
       export LIBPATH=$LD_LIBRARY_PATH
       RESOLV_MULTI=off ; export RESOLV_MULTI

- name: template oracle_client response file
  template: 
    src: "roles/oracle-client/files/oracle-client-{{oracle_client_version}}.rsp.j2"
    dest: "/tmp/oracle-client-{{oracle_client_version}}.rsp"

- name: install oracle_client
  shell : "source /home/siebel/.bash_profile && ./runInstaller -ignoreSysPrereqs -ignorePrereq -showProgress -invPtrLoc {{siebel_base_path}}/oracle_client/oraInventory/oraInst.loc -silent -waitforcompletion -responseFile /tmp/oracle-client-{{oracle_client_version}}.rsp"
  become: true
  become_user: siebel
  become_method: su
  args:
    executable: "/usr/bin/bash"
    chdir: "{{software_repository_path}}/oracle-client-{{target_platform}}-{{oracle_client_version}}/unarchive/client32"
    creates: "{{siebel_base_path}}/oracle_client/client"

- name: copy tnsnames.ora
  template: 
    src: "roles/oracle-client/files/oracle-client-tnsnames.ora.j2"
    dest: "{{siebel_base_path}}/oracle_client/client/network/admin/tnsnames.ora"