---
# tasks file for oracle-database
- name: install needed software
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
    - xdpyinfo
    - compat-libcap1
    - compat-libstdc++-33
    - sysstat
    - gcc
    - gcc-c++
    - ksh
    - glibc-devel
    - libaio-devel
    - nfs-utils
    - rpcbind
  when: ansible_distribution != "AIX"

- name: enable nfs-related services
  service:
   name: "{{ item }}"
   enabled: true
   state: started
  with_items:
  - rpcbind
  - nfs-lock
  when: ansible_distribution != "AIX"

- name: mount repository on linux
  mount:
    name: "/mnt{{ software_repository_path }}"
    src: "{{ hostvars[groups['repository-server'][0]]['ansible_default_ipv4']['address'] }}:{{ software_repository_path }}"
    fstype: nfs
    state: mounted
  when: ansible_distribution != "AIX"

- name: mount repository on aix
  command: /usr/sbin/mknfsmnt -f "/mnt{{ software_repository_path }}" -d "{{ software_repository_path }}" -h "{{ hostvars[groups['repository-server'][0]]['ansible_default_ipv4']['address'] }}" -M sys -N -a -t rw -w bg -Y -Z -X -H -j -q -g
  when: ansible_distribution == "AIX"	
  
- name: create groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - oinstall
    - dba
    - oper

- name: create user
  user:
    name: "{{ item }}"
    state: present
    group: oinstall
    groups: oinstall,dba,oper
  with_items:
    - oracle

- name: set limit_items
  set_fact:
    limit_items:  [ 'nproc', 'nproc' , 'nofile', 'nofile' , 'stack' ]
    limit_types:  [ 'soft' , 'hard'  , 'soft'  , 'hard'   , 'soft' ]
    limit_values: [ '2047' , '16384' , '4096'  , '65536'  , '10240' ]

- name: set os limits for user
  pam_limits:
    domain: oracle
    limit_item: "{{ item.0 }}"
    limit_type: "{{ item.1 }}"
    value: "{{ item.2 }}"
  with_together:
    - "{{ limit_items }}"
    - "{{ limit_types }}"
    - "{{ limit_values }}"  
  when: ansible_distribution != "AIX"	
  
- name: set os limits for user on AIX
  command: "chuser {{item}}=-1 oracle"
  with_items:
    - "fsize"
    - "data"
    - "stack"
    - "core"
    - "rss"
    - "nofiles"
    - "threads"
    - "nproc"
    - "cpu_hard"
    - "fsize_hard"
    - "data_hard"
    - "stack_hard"
    - "core_hard"
    - "rss_hard"
    - "nofiles_hard"
    - "threads_hard"
    - "nproc_hard"
  when: ansible_distribution == "AIX"	  
  
- name: set sysctl_items
  set_fact:
    sysctl_items:  ['fs.suid_dumpable','fs.aio-max-nr','fs.file-max','kernel.shmall','kernel.shmmax','kernel.shmmni','kernel.sem','net.ipv4.ip_local_port_range','net.core.rmem_default','net.core.rmem_max','net.core.wmem_default','net.core.wmem_max' ]
    sysctl_values:  [ '1','1048576','6815744','2097152','2271385600','4096','250 32000 100 128','9000 65500','262144','4194304','262144','1048586']
  when: ansible_distribution != "AIX"

- name: set sysctl settings
  sysctl:
    name: "{{item.0}}"
    value: "{{item.1}}"
    sysctl_set: yes
    state: present
    reload: yes
  with_together:
    - "{{ sysctl_items }}"
    - "{{ sysctl_values }}"
  when: ansible_distribution != "AIX"

- name: set selinux to premissive
  selinux:
    policy: targeted
    state: permissive
  when: ansible_distribution != "AIX"

- name: disable firewall
  service:
   name: "{{ item }}"
   enabled: false
   state: stopped
  with_items:
  - firewalld
  when: ansible_distribution != "AIX"
  
- name: create oracle_base
  file:
    path: "{{oracle_base_path}}/tmp"
    state: directory
    mode: 0775
    owner: oracle
    group: oinstall

- name: create oracle .bash_profile
  blockinfile:
    path: /home/oracle/.bash_profile
    create: yes
    block: |
      # Oracle Settings
      TMP={{oracle_base_path}}/tmp; export TMP
      TMPDIR=$TMP; export TMPDIR
      ORACLE_HOSTNAME={{ ansible_hostname }}; export ORACLE_HOSTNAME
      ORACLE_UNQNAME=orcl; export ORACLE_UNQNAME
      ORACLE_BASE={{oracle_base_path}}/base; export ORACLE_BASE
      ORACLE_HOME=$ORACLE_BASE/product/12.1.0/dbhome_1; export ORACLE_HOME
      ORACLE_SID=orcl; export ORACLE_SID
      PATH=/usr/sbin:$PATH; export PATH
      PATH=$ORACLE_HOME/bin:$PATH; export PATH
      LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib; export LD_LIBRARY_PATH
      export LIBPATH=$LD_LIBRARY_PATH	  
      CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib; export CLASSPATH

- name: template response file
  template: 
    src: "roles/oracle-database/files/oracle-{{oracle_version}}.rsp.j2"
    dest: "/tmp/oracle-{{oracle_version}}.rsp"

- name: run rootpre.sh on AIX
  command: "/mnt{{ software_repository_path }}/oracle-{{target_platform}}-{{ oracle_version }}/unarchive/database/rootpre.sh"
  when: ansible_distribution == "AIX"

- name: install oracle
  shell : "source /home/oracle/.bash_profile && echo y | ./runInstaller -ignoreSysPrereqs -ignorePrereq -showProgress -silent -waitforcompletion -responseFile /tmp/oracle-{{oracle_version}}.rsp"
  become: true
  become_user: oracle
  become_method: su
  args:
    chdir: "/mnt{{ software_repository_path }}/oracle-{{target_platform}}-{{ oracle_version }}/unarchive/database"
    creates: "{{oracle_base_path}}/base/product/12.1.0/dbhome_1/oraInst.loc"
    executable: "/usr/bin/bash"

- name: run orainstRoot.sh
  command: "{{oracle_base_path}}/oraInventory/orainstRoot.sh"
  args:
    creates: /etc/oraInst.loc

- name: run root.sh
  command: "{{oracle_base_path}}/base/product/12.1.0/dbhome_1/root.sh"
  args:
    creates: /etc/oratab

- name: template dbca response file
  template: 
    src: "roles/oracle-database/files/oracle-{{oracle_version}}.dbca.j2"
    dest: "/tmp/oracle-{{oracle_version}}-dbca.rsp"

- name: create instance
  shell : "source /home/oracle/.bash_profile && dbca -silent -createDatabase -cloneTemplate -responseFile /tmp/oracle-{{oracle_version}}-dbca.rsp"
  become: true
  become_user: oracle
  become_method: su
  args:
    executable: "/usr/bin/bash"
    creates: "{{oracle_base_path}}/base/oradata/orcl/system01.dbf"

- name: template netca response file
  template: 
    src: "roles/oracle-database/files/oracle-{{oracle_version}}.netca.j2"
    dest: "/tmp/oracle-{{oracle_version}}-netca.rsp"

- name: create listener
  shell : "source /home/oracle/.bash_profile && netca -silent -responseFile /tmp/oracle-{{oracle_version}}-netca.rsp"
  become: true
  become_user: oracle
  become_method: su
  args:
    executable: "/usr/bin/bash"	 	
    creates: "{{oracle_base_path}}/base/product/12.1.0/dbhome_1/network/admin/listener.ora"

- name: create autostart script
  template: 
    src: "roles/oracle-database/files/oracle-{{oracle_version}}.dbora.j2"
    dest: "/etc/dbora"
    mode: 0744

- name: patch oratab
  lineinfile:
    path: /etc/oratab
    regexp: "^orcl:"
    line: "orcl:{{oracle_base_path}}/base/product/12.1.0/dbhome_1:Y"

- name: make autostart
  lineinfile:
    path: /etc/inittab
    regexp: "^oracle:2:once:/etc/dbora"
    line: "oracle:2:once:/etc/dbora start > /dev/console 2>&1"

- name: patch rc.shutdown 
  lineinfile:
    path: /etc/rc.shutdown
    regexp: "^/etc/rc.oracle stop"
    line: "/etc/rc.oracle stop  > /dev/console 2>&1"