---
# tasks file for software-repository
- name: load mos credentrials
  include_vars: mos-credentials.yml

- include: get-websession.yml

- name: download
  include: download.yml
  with_items:
    - siebel-{{target_platform}}-{{siebel_version}}
    - siebel-win-{{siebel_version}}
    - oracle-{{target_platform}}-{{oracle_version}}
    - oracle-client-{{target_platform}}-{{oracle_client_version}}
    - ohs-{{target_platform}}-{{ohs_version}}
    - jdk-{{jdk_version}}
  loop_control:
    loop_var: product

- name: unarchive
  include: unarchive.yml
  with_items:
    - siebel-{{target_platform}}-{{siebel_version}}
    - siebel-win-{{siebel_version}}
    - oracle-{{target_platform}}-{{oracle_version}}
    - oracle-client-{{target_platform}}-{{oracle_client_version}}
    - ohs-{{target_platform}}-{{ohs_version}}
    - jdk-{{jdk_version}}
  loop_control:
    loop_var: product

- name: create directory license_codes
  file:
    path: "{{software_repository_path}}/license_codes"
    state: directory
    mode: 0755

- name: download licence codes
  get_url:
    url: http://www.oracle.com/ocom/groups/public/@ocom/documents/webcontent/license_code.xml
    dest: "{{software_repository_path}}/license_codes/"
    timeout: 20
    force: no

- name: install jdk
  include: install-jdk.yml
  when: ansible_distribution != "AIX"

- name: create siebel install image
  include: create-siebel-install-image.yml

- name: install nfs service
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
    - nfs-utils
  when: ansible_distribution != "AIX"

- name: export repository via nfs
  lineinfile:
    path: /etc/exports
    line: "{{ software_repository_path }}        *(rw)"
    create: yes
  when: ansible_distribution != "AIX"	

- name: enable service nfs-server linux
  systemd:
    name: nfs-server
    enabled: yes
    state: restarted
  when: ansible_distribution != "AIX"
  
- name: export repository vio nfs on aix
  command: /usr/sbin/mknfsexp -d {{ software_repository_path }} -P -B -S "sys,krb5p,krb5i,krb5,dh" -t rw
  when: ansible_distribution == "AIX"
