---
# tasks file for software-repository
- name: load mos credentrials
  include_vars: mos-credentials.yml

- include: get-websession.yml

- name: download
  include: download.yml
  with_items:
    - siebel-{{target_platform}}-{{siebel_version}}
    - siebel-win-{{siebel_version}}
    - oracle-{{target_platform}}-{{oracle_version}}
    - oracle-client-{{target_platform}}-{{oracle_client_version}}
    - ohs-{{target_platform}}-{{ohs_version}}
    - jdk-{{jdk_version}}
  loop_control:
    loop_var: product

- name: unarchive
  include: unarchive.yml
  with_items:
    - siebel-{{target_platform}}-{{siebel_version}}
    - siebel-win-{{siebel_version}}
    - oracle-{{target_platform}}-{{oracle_version}}
    - oracle-client-{{target_platform}}-{{oracle_client_version}}
    - ohs-{{target_platform}}-{{ohs_version}}
    - jdk-{{jdk_version}}
  loop_control:
    loop_var: product

- name: install jdk
  include: install-jdk.yml
  when: ansible_distribution != "AIX"

- name: create siebel install image
  include: create-siebel-install-image.yml

- name: install nfs service
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
    - nfs-utils
  when: ansible_distribution != "AIX"

- name: export repository via nfs
  lineinfile:
    path: /etc/exports
    line: "{{ software_repository_path }}        *(rw,sync,no_subtree_check)"

- name: enable service nfs-server linux
  systemd:
    name: nfs-server
    enabled: yes
    state: restarted
  when: ansible_distribution != "AIX"
