- name: create dbenv.sh
  shell : "source /home/siebel/.bash_profile && ./CreateDbSrvrEnvScript {{siebel_base_path}}/ses/Siebel/ses ENU Oracle"
  become: true
  become_user: siebel
  become_method: su
  args:
    chdir: "{{siebel_base_path}}/ses/Siebel/ses/siebsrvr/install_script/install"
    executable: "/usr/bin/bash"
    creates: "{{siebel_base_path}}/ses/Siebel/ses/siebsrvr/dbenv.sh"

- name: template create tablespaces sql
  template: 
    src: roles/siebel-server/files/create_tablespace.sql.j2
    dest: "/tmp/create_tablespace_{{item}}.sql"
  with_items:
    - "SDATA"
    - "SINDEX"

- name: create tablespaces
  shell : "source /home/siebel/.bash_profile && echo '{{oracle_passwd}}'| sqlplus system@orcl @/tmp/create_tablespace_{{item}}.sql"
  become: true
  become_user: siebel
  become_method: su
  args:
    executable: "/usr/bin/bash"
    creates: "{{oracle_base_path}}/oracle/base/oradata/orcl/{{item}}.dbf"
  with_items:
    - "SDATA"
    - "SINDEX"

- name: template grantusr sql
  template: 
    src: roles/siebel-server/files/grantusr.sql.j2
    dest: "/tmp/grantusr.sql"

- name: run grantusr sql
  shell : "source /home/siebel/.bash_profile && echo '{{oracle_passwd}}'| sqlplus system@orcl @/tmp/grantusr.sql"
  become: true
  become_user: siebel
  become_method: su
  args:
    executable: "/usr/bin/bash"

- name: template install_db_master.ucf
  template: 
    src: roles/siebel-server/files/install_db_master.ucf.j2
    dest: "/tmp/install_db_master.ucf"
    owner: "siebel"
    group: "sse_role"

- name: create siebel database
  shell : "source /home/siebel/.bash_profile && source {{siebel_base_path}}/ses/Siebel/ses/siebsrvr/dbenv.sh && srvrupgwiz /m /tmp/install_db_master.ucf"
  become: true
  become_user: siebel
  become_method: su
  args:
    executable: "/usr/bin/bash"
	
- name: enable lic codes
  shell : "source /home/siebel/.bash_profile && echo 'update siebel.s_app_key set INACTIVE_FLG='N' where INACTIVE_FLG='Y';commit;'| sqlplus sadmin/nimdas@orcl"
  become: true
  become_user: siebel
  become_method: su
  args:
    executable: "/usr/bin/bash"