---
# tasks file for siebel server
- name: enable nfs-related services
  service:
   name: "{{ item }}"
   enabled: true
   state: started
  with_items:
  - rpcbind
  - nfs-lock
  when: ansible_distribution != "AIX"

- name: mount repository on linux
  mount:
    name: "/mnt{{ software_repository_path }}"
    src: "{{ hostvars[groups['repository-server'][0]]['ansible_default_ipv4']['address'] }}:{{ software_repository_path }}"
    fstype: nfs
    state: mounted
  when: ansible_distribution != "AIX"

- name: mount repository on aix
  command: /usr/sbin/mknfsmnt -f "/mnt{{ software_repository_path }}" -d "{{ software_repository_path }}" -h "{{ hostvars[groups['repository-server'][0]]['ansible_default_ipv4']['address'] }}" -M sys -N -a -t rw -w bg -Y -Z -X -H -j -q -g
  when: ansible_distribution == "AIX"

- name: create groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - sse_role

- name: create user
  user:
    name: "{{ item }}"
    state: present
    group: sse_role
    groups: sse_role,oinstall
  with_items:
    - siebel

- name: create siebel_base
  file:
    path: "{{item}}"
    state: directory
    mode: 0775
    owner: siebel
    group: sse_role
  with_items:
    - "{{siebel_base_path}}"
    - "{{siebel_base_path}}/ses/oraInventory/"

- name: create siebel ses oraInventory
  blockinfile:
    path: "{{siebel_base_path}}/ses/oraInventory/oraInst.loc"
    create: yes
    mode: 0775
    owner: siebel
    group: sse_role
    block: |
       inventory_loc={{siebel_base_path}}/ses/oraInventory
       inst_group=siebel

- name: get java_home on linux
  find:
    paths: "/opt/"
    patterns: "jdk*"
    file_type: directory
  register: java_home
  when: ansible_distribution != "AIX"
  
- name: get java_home on aix
  find:
    paths: "/usr/"
    patterns: "java71_64"
    file_type: directory
  register: java_home
  when: ansible_distribution == "AIX"

- name: create siebel .bash_profile
  blockinfile:
    path: /home/siebel/.bash_profile
    create: yes
    block: |	   
       # Oracle Settings
       TMP={{siebel_base_path}}/tmp; export TMP
       TMPDIR=$TMP; export TMPDIR
       ORACLE_BASE={{siebel_base_path}}/oracle_client; export ORACLE_BASE
       ORACLE_HOME={{siebel_base_path}}/oracle_client/client; export ORACLE_HOME
       ORACLE_SID=orcl; export ORACLE_SID
       PATH=/usr/sbin:$PATH; export PATH
       PATH=$ORACLE_HOME/bin:$PATH; export PATH
       LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib; export LD_LIBRARY_PATH
       export LIBPATH=$LD_LIBRARY_PATH
       RESOLV_MULTI=off ; export RESOLV_MULTI

- name: template install ses response file
  template: 
    src: roles/siebel-server/files/siebel-{{siebel_version}}-install-ses.rsp.j2
    dest: /tmp/siebel-{{siebel_version}}-install-ses.rsp

- name: install ses
  shell : "source /home/siebel/.bash_profile && ./runInstaller -silent -waitforcompletion -responseFile /tmp/siebel-{{siebel_version}}-install-ses.rsp -jreloc {{java_home.files[0].path}} -invPtrLoc {{siebel_base_path}}/ses/oraInventory/oraInst.loc"
  become: true
  become_user: siebel
  become_method: su
  args:
    chdir: "{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_version }}/Siebel_Install_Image/16.0.0.0/AIX/Server/Siebel_Enterprise_Server/Disk1/install"
    executable: "/usr/bin/bash"
    creates: "{{siebel_base_path}}/ses/16.0.0.0.0/ses/siebsrvr/cfgenv.sh"

- name: template .odbc.ini
  template: 
    src: roles/siebel-server/files/odbc.ini.j2
    dest: "{{siebel_base_path}}/ses/16.0.0.0.0/ses/siebsrvr/sys/.odbc.ini"
    owner: "siebel"
    group: "sse_role"

- name: check existing siebel database
  shell : "source /home/siebel/.bash_profile && echo 'select name from siebel.s_repository;' | sqlplus sadmin/nimdas@orcl"
  become: true
  become_user: siebel
  become_method: su
  args:
    executable: "/usr/bin/bash"
  register: siebel_database_exists

- name: create siebel database
  include: create-siebel-database.yml
  when: siebel_database_exists.stdout.find("Siebel Repository") == -1

- name: template config siebelserver response file
  template: 
    src: roles/siebel-server/files/config-siebelserver-{{siebel_version}}.rsp.j2
    dest: /tmp/config-siebelserver-{{siebel_version}}.rsp

- name: config siebelserver
  shell : "source /home/siebel/.bash_profile && source {{siebel_base_path}}/ses/16.0.0.0.0/ses/siebsrvr/cfgenv.sh && ./config.sh -mode siebsrvr -responseFile /tmp/config-siebelserver-{{siebel_version}}.rsp"
  become: true
  become_user: siebel
  become_method: su
  args:
    chdir: "{{siebel_base_path}}/ses/16.0.0.0.0/ses/config"
    executable: "/usr/bin/bash"
    creates: "{{siebel_base_path}}/ses/16.0.0.0.0/ses/siebsrvr/sys/svc.siebsrvr.SBA_82:{{ansible_hostname}}"