---
# tasks file for siebel server
- name: create siebel ses oraInventory
  blockinfile:
    path: "{{siebel_base_path}}/ses/oraInventory/oraInst.loc"
    create: yes
    mode: 0775
    owner: siebel
    group: sse_role
    block: |
       inventory_loc={{siebel_base_path}}/ses/oraInventory
       inst_group=siebel

- name: template install ses response file
  template: 
    src: roles/siebel-server/files/siebel-{{siebel_version}}-install-ses.rsp.j2
    dest: /tmp/siebel-{{siebel_version}}-install-ses.rsp

- name: install ses
  shell : "source /home/siebel/.bash_profile && ./runInstaller -silent -waitforcompletion -responseFile /tmp/siebel-{{siebel_version}}-install-ses.rsp -jreloc {{java_home}} -invPtrLoc {{siebel_base_path}}/ses/oraInventory/oraInst.loc"
  become: true
  become_user: siebel
  become_method: su
  args:
    chdir: "{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_version }}/Siebel_Install_Image/{{ siebel_version }}/{{target_platform}}/Server/Siebel_Enterprise_Server/Disk1/install"
    executable: "/usr/bin/bash"
    creates: "{{siebel_base_path}}/ses/Siebel/ses/siebsrvr"

#- name: template .odbc.ini
#  template: 
#    src: roles/siebel-server/files/odbc.ini.j2
#    dest: "{{siebel_base_path}}/ses/{{ siebel_version }}.0/ses/siebsrvr/sys/.odbc.ini"
#    owner: "siebel"
#    group: "sse_role"
#
- name: check existing siebel database
  shell : "source /home/siebel/.bash_profile && echo 'select name from siebel.s_repository;' | sqlplus sadmin/nimdas@orcl"
  become: true
  become_user: siebel
  become_method: su
  args:
    executable: "/usr/bin/bash"
  register: siebel_database_exists

- name: create siebel database
  include: create-siebel-database.yml
  when: siebel_database_exists.stdout.find("Siebel Repository") == -1

#- name: template config siebelserver response file
#
#  template: 
#    src: roles/siebel-server/files/config-siebelserver-{{siebel_version}}.rsp.j2
#    dest: /tmp/config-siebelserver-{{siebel_version}}.rsp
#
#- name: config siebelserver
#  shell : "source /home/siebel/.bash_profile && source {{siebel_base_path}}/ses/{{ siebel_version }}.0/ses/siebsrvr/cfgenv.sh && ./config.sh -mode siebsrvr -responseFile /tmp/config-siebelserver-{{siebel_version}}.rsp"
#  become: true
#  become_user: siebel
#  become_method: su
#  args:
#    chdir: "{{siebel_base_path}}/ses/{{ siebel_version }}.0/ses/config"
#    executable: "/usr/bin/bash"
#    creates: "{{siebel_base_path}}/ses/{{ siebel_version }}.0/ses/siebsrvr/sys/svc.siebsrvr.SBA_82:{{ansible_hostname}}"
