---
# tasks file for siebel gateway
- name: create siebel gw oraInventory
  blockinfile:
    path: "{{siebel_base_path}}/gw/oraInventory/oraInst.loc"
    create: yes
    mode: 0775
    owner: siebel
    group: sse_role
    block: |
       inventory_loc={{siebel_base_path}}/gw/oraInventory
       inst_group=siebel

- name: template install gateway response file
  template: 
    src: roles/siebel-gateway/files/siebel-{{siebel_version}}-install-gw.rsp.j2
    dest: /tmp/siebel-{{siebel_version}}-install-gw.rsp
#TODO create chain of trust
#TODO use correct java path
- name: install gateway
  shell : "source /home/siebel/.bash_profile && ./runInstaller -silent -waitforcompletion -responseFile /tmp/siebel-{{siebel_version}}-install-gw.rsp -jreloc /opt/jdk{{jdk_version}} -invPtrLoc {{siebel_base_path}}/gw/oraInventory/oraInst.loc"
  become: true
  become_user: siebel
  become_method: su
  args:
    chdir: "{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_version }}/Siebel_Install_Image/{{siebel_version}}/{{target_platform}}/Server/Siebel_Enterprise_Server/Disk1/install"
    executable: "/usr/bin/bash"
    creates: "{{siebel_base_path}}/gw/{{siebel_version}}.0/ses/gtwysrvr/cfgenv.sh"

#- name: template config gateway response file
#  template: 
#    src: roles/siebel-gateway/files/siebel-{{siebel_version}}-config-gw.rsp.j2
#    dest: /tmp/siebel-{{siebel_version}}-config-gw.rsp
#
#- name: config gateway
#  shell : "source /home/siebel/.bash_profile && source {{siebel_base_path}}/gw/16.0.0.0.0/ses/gtwysrvr/cfgenv.sh && ./config.sh -mode enterprise  -responseFile /tmp/siebel-{{siebel_version}}-config-gw.rsp"
#  become: true
#  become_user: siebel
#  become_method: su
#  args:
#    chdir: "{{siebel_base_path}}/gw/16.0.0.0.0/ses/config"
#    executable: "/usr/bin/bash"
#    creates: "{{siebel_base_path}}/gw/16.0.0.0.0/ses/gtwysrvr/sys/siebns.dat"
#
#- name: template config enterprise response file
#  template: 
#    src: roles/siebel-gateway/files/siebel-{{siebel_version}}-config-enterprise.rsp.j2
#    dest: /tmp/siebel-{{siebel_version}}-config-enterprise.rsp
#
#- name: config enterprise
#  shell : "source /home/siebel/.bash_profile && source {{siebel_base_path}}/gw/16.0.0.0.0/ses/gtwysrvr/siebenv.sh && ./config.sh -mode enterprise  -responseFile /tmp/siebel-{{siebel_version}}-config-enterprise.rsp"
#  become: true
#  become_user: siebel
#  become_method: su
#  args:
#    chdir: "{{siebel_base_path}}/gw/16.0.0.0.0/ses/config"
#    executable: "/usr/bin/bash"
#    creates: "{{siebel_base_path}}/gw/16.0.0.0.0/ses/gtwysrvr/fs/att"
#
#- name: template config swe_profile response file
#  template: 
#    src: roles/siebel-gateway/files/siebel-{{siebel_version}}-config-swe_profile.rsp.j2
#    dest: /tmp/siebel-{{siebel_version}}-config-swe_profile.rsp
#
#- name: config swe_profile
#  shell : "source /home/siebel/.bash_profile && source {{siebel_base_path}}/gw/16.0.0.0.0/ses/gtwysrvr/siebenv.sh && ./config.sh -mode enterprise  -responseFile /tmp/siebel-{{siebel_version}}-config-swe_profile.rsp"
#  become: true
#  become_user: siebel
#  become_method: su
#  args:
#    chdir: "{{siebel_base_path}}/gw/16.0.0.0.0/ses/config"
#    executable: "/usr/bin/bash"
#    creates: "{{siebel_base_path}}/gw/16.0.0.0.0/ses/gtwysrvr/admin/Webserver/eapps.cfg"	
