---
# tasks file for siebel application interface
- name: install needed software
  yum:
    name: tcsh
  when: ansible_distribution != "AIX"
#TODO install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 8

- name: enable nfs-related services
  service:
   name: "{{ item }}"
   enabled: true
   state: started
  with_items:
  - rpcbind
  - nfs-lock
  when: ansible_distribution != "AIX"

- name: mount repository on linux
  mount:
    name: "/mnt{{ software_repository_path }}"
    src: "{{ hostvars[groups['repository-server'][0]]['ansible_default_ipv4']['address'] }}:{{ software_repository_path }}"
    fstype: nfs
    state: mounted
  when: ansible_distribution != "AIX"

- name: mount repository on aix
  command: /usr/sbin/mknfsmnt -f "/mnt{{ software_repository_path }}" -d "{{ software_repository_path }}" -h "{{ hostvars[groups['repository-server'][0]]['ansible_default_ipv4']['address'] }}" -M sys -N -a -t rw -w bg -Y -Z -X -H -j -q -g
  when: ansible_distribution == "AIX"

- name: create groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - sse_role

- name: create user
  user:
    name: "{{ item }}"
    state: present
    group: sse_role
    groups: sse_role,oinstall
  with_items:
    - siebel

- name: create siebel_base
  file:
    path: "{{item}}"
    state: directory
    mode: 0775
    owner: siebel
    group: sse_role
  with_items:
    - "{{siebel_base_path}}"
    - "{{siebel_base_path}}/ai/oraInventory"

- name: create siebel ai oraInventory
  blockinfile:
    path: "{{siebel_base_path}}/ai/oraInventory/oraInst.loc"
    create: yes
    mode: 0775
    owner: siebel
    group: sse_role
    block: |
       inventory_loc={{siebel_base_path}}/ai/oraInventory
       inst_group=siebel

- name: get java_home on linux
  find:
    paths: "/opt/"
    patterns: "jdk*"
    file_type: directory
  register: java_home
  when: ansible_distribution != "AIX"
  
- name: get java_home on aix
  find:
    paths: "/usr/"
    patterns: "java8_64"
    file_type: directory
  register: java_home
  when: ansible_distribution == "AIX"

- name: create siebel .bash_profile
  blockinfile:
    path: /home/siebel/.bash_profile
    create: yes
    block: |
       # Oracle Settings
       TMP={{siebel_base_path}}/tmp; export TMP
       TMPDIR=$TMP; export TMPDIR
       ORACLE_BASE={{siebel_base_path}}/oracle_client; export ORACLE_BASE
       ORACLE_HOME={{siebel_base_path}}/oracle_client/client; export ORACLE_HOME
       ORACLE_SID=orcl; export ORACLE_SID
       PATH=/usr/sbin:$PATH; export PATH
       PATH=$ORACLE_HOME/bin:$PATH; export PATH
       LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib; export LD_LIBRARY_PATH
       export LIBPATH=$LD_LIBRARY_PATH
       RESOLV_MULTI=off ; export RESOLV_MULTI

- name: template install appinterface response file
  template: 
    src: roles/siebel-ai/files/siebel-{{siebel_version}}-install-ai.rsp.j2
    dest: /tmp/siebel-{{siebel_version}}-install-ai.rsp
#TODO create chain of trust
#TODO Install unrestrictedpolicyfiles.zip in JAVA Home
#TODO ln -s /usr/java8_64/jre /opt/siebel/ai/Siebel/jre
- name: install appinterface
  shell : "source /home/siebel/.bash_profile && ./runInstaller -silent -waitforcompletion -responseFile /tmp/siebel-{{siebel_version}}-install-ai.rsp -jreloc /opt/jdk1.8.0_144 -invPtrLoc {{siebel_base_path}}/ai/oraInventory/oraInst.loc"
  become: true
  become_user: siebel
  become_method: su
  args:
    chdir: "{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_version }}/Siebel_Install_Image/{{siebel_version}}/{{target_platform}}/Server/Siebel_Enterprise_Server/Disk1/install"
    executable: "/usr/bin/bash"
    creates: "{{siebel_base_path}}/ai/Siebel"
