---
# tasks file for siebel application interface

#TODO install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 8

- name: create siebel ai oraInventory
  blockinfile:
    path: "{{siebel_base_path}}/ai/oraInventory/oraInst.loc"
    create: yes
    mode: 0775
    owner: siebel
    group: sse_role
    block: |
       inventory_loc={{siebel_base_path}}/ai/oraInventory
       inst_group=siebel

- name: template install appinterface response file
  template: 
    src: roles/siebel-ai/files/siebel-{{siebel_version}}-install-ai.rsp.j2
    dest: /tmp/siebel-{{siebel_version}}-install-ai.rsp
#TODO create chain of trust
#TODO Install unrestrictedpolicyfiles.zip in JAVA Home
#TODO ln -s /usr/java8_64/jre /opt/siebel/ai/Siebel/jre
- name: install appinterface
  shell : "source /home/siebel/.bash_profile && ./runInstaller -silent -waitforcompletion -responseFile /tmp/siebel-{{siebel_version}}-install-ai.rsp -jreloc /opt/jdk1.8.0_144 -invPtrLoc {{siebel_base_path}}/ai/oraInventory/oraInst.loc"
  become: true
  become_user: siebel
  become_method: su
  args:
    chdir: "{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_version }}/Siebel_Install_Image/{{siebel_version}}/{{target_platform}}/Server/Siebel_Enterprise_Server/Disk1/install"
    executable: "/usr/bin/bash"
    creates: "{{siebel_base_path}}/ai/Siebel"
