- name: template snic file linux server
  template: 
    src: roles/siebel-repository/files/siebel-linux.rsp.j2
    dest: /tmp/sisbel-linux.rsp

- name: template snic file sample database
  template: 
    src: roles/siebel-repository/files/siebel-sample.rsp.j2
    dest: /tmp/siebel-sample.rsp

- name: get java_home for snic
  find:
    paths: "/opt/"
    patterns: "jdk*"
    file_type: directory
  register: java_home

- name: check if we ran before server
  stat:
    path: "{{ siebel_repository_path }}/siebel-{{ siebel_version }}/Siebel_Install_Image/products.txt"
  register: server_install_image

- name: check if we ran before sample
  stat:
    path: "{{ siebel_repository_path }}/siebel-win-{{ siebel_version }}/Siebel_Install_Image/products.txt"
  register: sample_install_image

- name: run snic.sh server
  command: ./snic.sh -silent -responseFile /tmp/sisbel-linux.rsp
  args:
    chdir: "{{ siebel_repository_path }}/siebel-{{ siebel_version }}/unarchive"
  when:
    server_install_image.stat.exists == false
  environment:
    JAVA_HOME: "{{java_home.files[0].path}}"
    LANG: "C"


- name: run snic.sh sample
  command: ./snic.sh -silent -responseFile /tmp/siebel-sample.rsp
  args:
    chdir: "{{ siebel_repository_path }}/siebel-win-{{ siebel_version }}/unarchive"
  when:
    sample_install_image.stat.exists == false
  environment:
    JAVA_HOME: "{{java_home.files[0].path}}"
    LANG: "C"


