---
# tasks file for siebel-repository
- name: load mos credentrials
  include_vars: mos-credentials.yml

- include: get-websession.yml

- name: download
  include: download.yml
  with_items:
    - siebel-{{siebel_version}}
    - siebel-win-{{siebel_version}}
    - oracle-{{oracle_version}}
    - oracle-client-{{oracle_client_version}}
    - ohs-{{ohs_version}}
    - jdk-{{jdk_version}}
  loop_control:
    loop_var: product

- name: unarchive
  include: unarchive.yml
  with_items:
    - siebel-{{siebel_version}}
    - siebel-win-{{siebel_version}}
    - oracle-{{oracle_version}}
    - oracle-client-{{oracle_client_version}}
    - ohs-{{ohs_version}}
    - jdk-{{jdk_version}}
  loop_control:
    loop_var: product

- name: install jdk
  include: install-jdk.yml

- name: create siebel install image
  include: create-siebel-install-image.yml

- name: install nfs service
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
    - nfs-utils

- name: export repository via nfs
  lineinfile:
    path: /etc/exports
    line: "{{ siebel_repository_path }}        *(rw,sync,no_subtree_check)"

- name: enable service nfs-server
  systemd:
    name: nfs-server
    enabled: yes
    state: restarted
